name: Whole system tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-and-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter test
      - run: flutter driver --target=test_driver/app.dart -d macos
      - name: upload screenshot
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: /tmp/screenshots

 
