name: Whole system tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-and-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter test
      - name: "List all simulators"
          run: "xcrun instruments -s"
      - name: "Start simulator"
        run: |
          UDID=$(
            xcrun instruments -s |
            awk \
              -F ' *[][]' \
              -v 'device=iPhone 11 Pro (13.4.1)' \
              '$1 == device { print $2 }'
          )
          xcrun simctl boot "${UDID:?No Simulator with this name found}"
      - run: flutter driver --target=test_driver/app.dart -d macos
      - run: flutter driver --target=test_driver/app.dart -d iPhone 11 Pro
      - name: upload screenshot
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: /tmp/screenshots

 
