name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Checkout repo code using v1 of standard checkout Action
    - uses: actions/checkout@v1
      # Uses community Action to install Flutter
    - uses: subosito/flutter-action@v1.3.0
      with:
        flutter-version: '1.18.0-dev.5.0'
        channel: 'dev'
    # Runs a single command using the runners shell
    - run: flutter pub get
    - run: flutter analyze
    - run: flutter test

 
